markdown: kramdown
# Site settings
titre:
  fr: "Annalí Casanueva Artís - Page professionnelle"
  en: "Annalí Casanueva Artís - Professional page"
baseurl: ""

color-green: "#017100"
color-red: "#800000"
color-grey: "#AAAAAA"

exclude:
 - CNAME
 - README.md
 - cvdata.ini

#gems:
#  - jekyll-redirect-from
